### PR TITLE
Revert the widget ID fix to replicate new field

### PR DESCRIPTION
**Pull request by shivapoudel**
Adding repeater field in one widget replicates the same settings field to another repeater field on adding to new widget.

### CODE REVIEW

**Comment by shivapoudel** [comment]
@nimatg This was the effect of https://github.com/themegrill/flash-toolkit/commit/0f582baabbf7cffe22f602d4d8c6f5ef4829f956, do you have any idea why we introduced it.

**Comment by nimatg** [comment]
@shivapoudel  
When you add widget_id, it will not save the newly created field in the those widgets which have repeater field. And remember that these problem is only occured in the widget area but fine in the page builder.

**Comment by shivapoudel** [comment]
@nimatg Agreed. We have done this for the widget area, I rememberd now. @ashishsthanp Although the current issue is resolved but we have to keep similar for the widget area. Hence, we have to review this again :)

**Comment by ashishsthanp** [comment]
@nimatg Can you explain what was the actual issue you've faced in repeater field before? Since the changes made by @shivapoudel to fix that issue you've mentioned, caused another issue on the repeater field Page Builder page.

**Comment by shivapoudel** [comment]
Additional: https://github.com/themegrill/flash-toolkit/commit/1159602e893bb37a4a9c7ec5676be9f4c7e5fab5

**Pull request merged**
